/**
 * Client-side document generation: converts Crisp output text → downloadable DOCX or PDF.
 */

import { saveAs } from "file-saver";

// ─── Helpers ───

/** Parse simple structured text into sections. Handles headers prefixed with # or ALL-CAPS lines. */
function parseSections(text: string): { title: string; body: string }[] {
  const lines = text.split("\n");
  const sections: { title: string; body: string }[] = [];
  let currentTitle = "";
  let currentBody: string[] = [];

  for (const line of lines) {
    const headerMatch = line.match(/^#{1,3}\s+(.+)/);
    const capsMatch = line.match(/^([A-Z][A-Z\s:]{4,})$/);

    if (headerMatch || capsMatch) {
      if (currentTitle || currentBody.length > 0) {
        sections.push({ title: currentTitle, body: currentBody.join("\n").trim() });
      }
      currentTitle = (headerMatch?.[1] || capsMatch?.[1] || "").trim();
      currentBody = [];
    } else {
      currentBody.push(line);
    }
  }

  if (currentTitle || currentBody.length > 0) {
    sections.push({ title: currentTitle, body: currentBody.join("\n").trim() });
  }

  return sections;
}

// ─── DOCX Export ───

export async function exportToDocx(content: string, filename: string = "crisp-output"): Promise<void> {
  const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } = await import("docx");

  const sections = parseSections(content);
  const children: InstanceType<typeof Paragraph>[] = [];

  // Title
  children.push(
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 300 },
      children: [
        new TextRun({
          text: filename.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()),
          bold: true,
          size: 32,
          font: "Calibri",
        }),
      ],
    })
  );

  for (const section of sections) {
    if (section.title) {
      children.push(
        new Paragraph({
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 240, after: 120 },
          children: [
            new TextRun({
              text: section.title,
              bold: true,
              size: 26,
              font: "Calibri",
            }),
          ],
        })
      );
    }

    if (section.body) {
      const bodyLines = section.body.split("\n");
      for (const line of bodyLines) {
        const bulletMatch = line.match(/^[\s]*[-•*]\s+(.*)/);
        if (bulletMatch) {
          children.push(
            new Paragraph({
              bullet: { level: 0 },
              spacing: { after: 60 },
              children: [
                new TextRun({
                  text: bulletMatch[1],
                  size: 22,
                  font: "Calibri",
                }),
              ],
            })
          );
        } else if (line.trim()) {
          children.push(
            new Paragraph({
              spacing: { after: 120 },
              children: [
                new TextRun({
                  text: line.trim(),
                  size: 22,
                  font: "Calibri",
                }),
              ],
            })
          );
        }
      }
    }
  }

  // Footer
  children.push(
    new Paragraph({
      spacing: { before: 400 },
      children: [
        new TextRun({
          text: "Generated by Crisp",
          italics: true,
          size: 18,
          color: "888888",
          font: "Calibri",
        }),
      ],
    })
  );

  const doc = new Document({
    sections: [{ children }],
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, `${filename}.docx`);
}

// ─── PDF Export ───

export async function exportToPdf(content: string, filename: string = "crisp-output"): Promise<void> {
  const { default: jsPDF } = await import("jspdf");

  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const maxWidth = pageWidth - margin * 2;
  let y = margin;

  const addPageIfNeeded = (requiredSpace: number) => {
    if (y + requiredSpace > doc.internal.pageSize.getHeight() - margin) {
      doc.addPage();
      y = margin;
    }
  };

  // Title
  const titleText = filename.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(30, 30, 30);
  const titleLines = doc.splitTextToSize(titleText, maxWidth);
  addPageIfNeeded(titleLines.length * 8 + 10);
  doc.text(titleLines, pageWidth / 2, y, { align: "center" });
  y += titleLines.length * 8 + 10;

  // Divider
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  const sections = parseSections(content);

  for (const section of sections) {
    if (section.title) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(13);
      doc.setTextColor(40, 40, 40);
      const headingLines = doc.splitTextToSize(section.title, maxWidth);
      addPageIfNeeded(headingLines.length * 6 + 8);
      doc.text(headingLines, margin, y);
      y += headingLines.length * 6 + 4;
    }

    if (section.body) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);
      doc.setTextColor(50, 50, 50);

      const bodyLines = section.body.split("\n");
      for (const line of bodyLines) {
        const bulletMatch = line.match(/^[\s]*[-•*]\s+(.*)/);
        const textToRender = bulletMatch ? `  \u2022  ${bulletMatch[1]}` : line.trim();

        if (!textToRender) {
          y += 3;
          continue;
        }

        const wrapped = doc.splitTextToSize(textToRender, maxWidth);
        addPageIfNeeded(wrapped.length * 5 + 2);
        doc.text(wrapped, margin, y);
        y += wrapped.length * 5 + 2;
      }
      y += 4;
    }
  }

  // Footer on last page
  doc.setFont("helvetica", "italic");
  doc.setFontSize(9);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by Crisp", pageWidth / 2, doc.internal.pageSize.getHeight() - 10, {
    align: "center",
  });

  doc.save(`${filename}.pdf`);
}
