/**
 * Client-side document generation: converts Crisp output text → downloadable DOCX or PDF.
 * Supports custom branding (fonts, colors, logo, footer).
 */

import { saveAs } from "file-saver";
import type { DocumentBranding } from "./store";

// ─── Helpers ───

/** Parse simple structured text into sections. Handles headers prefixed with # or ALL-CAPS lines. */
function parseSections(text: string): { title: string; body: string }[] {
  const lines = text.split("\n");
  const sections: { title: string; body: string }[] = [];
  let currentTitle = "";
  let currentBody: string[] = [];

  for (const line of lines) {
    const headerMatch = line.match(/^#{1,3}\s+(.+)/);
    const capsMatch = line.match(/^([A-Z][A-Z\s:]{4,})$/);

    if (headerMatch || capsMatch) {
      if (currentTitle || currentBody.length > 0) {
        sections.push({ title: currentTitle, body: currentBody.join("\n").trim() });
      }
      currentTitle = (headerMatch?.[1] || capsMatch?.[1] || "").trim();
      currentBody = [];
    } else {
      currentBody.push(line);
    }
  }

  if (currentTitle || currentBody.length > 0) {
    sections.push({ title: currentTitle, body: currentBody.join("\n").trim() });
  }

  return sections;
}

/** Convert hex color to RGB array */
function hexToRgb(hex: string): [number, number, number] {
  const clean = hex.replace("#", "");
  const r = parseInt(clean.substring(0, 2), 16) || 0;
  const g = parseInt(clean.substring(2, 4), 16) || 0;
  const b = parseInt(clean.substring(4, 6), 16) || 0;
  return [r, g, b];
}

// ─── DOCX Export ───

export async function exportToDocx(
  content: string,
  filename: string = "crisp-output",
  branding?: DocumentBranding
): Promise<void> {
  const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, ImageRun, Footer } = await import("docx");

  const font = branding?.fontBody || "Calibri";
  const headingFont = branding?.fontHeading || font;
  const primaryHex = (branding?.primaryColor || "#1a1a2e").replace("#", "");
  const accentHex = (branding?.accentColor || "#10b981").replace("#", "");
  const footerText = branding?.footerText || "Generated by Crisp";

  const sections = parseSections(content);
  const children: InstanceType<typeof Paragraph>[] = [];

  // Branded header with company name + accent bar
  if (branding?.headerStyle === "branded" || branding?.headerStyle === "full") {
    const headerChildren: InstanceType<typeof TextRun | typeof ImageRun>[] = [];

    if (branding.logoUrl && branding.logoUrl.startsWith("data:")) {
      try {
        const base64 = branding.logoUrl.split(",")[1];
        const buffer = Uint8Array.from(atob(base64), (c) => c.charCodeAt(0));
        headerChildren.push(
          new ImageRun({
            data: buffer,
            transformation: { width: 40, height: 40 },
            type: "png",
          })
        );
      } catch {
        // Skip logo if decode fails
      }
    }

    if (branding.companyName) {
      headerChildren.push(
        new TextRun({
          text: branding.companyName,
          bold: true,
          size: 20,
          font: headingFont,
          color: primaryHex,
        })
      );
    }

    if (headerChildren.length > 0) {
      children.push(
        new Paragraph({
          spacing: { after: 200 },
          children: headerChildren,
        })
      );
    }
  }

  // Title
  children.push(
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 300 },
      children: [
        new TextRun({
          text: filename.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()),
          bold: true,
          size: 32,
          font: headingFont,
          color: primaryHex,
        }),
      ],
    })
  );

  for (const section of sections) {
    if (section.title) {
      children.push(
        new Paragraph({
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 240, after: 120 },
          children: [
            new TextRun({
              text: section.title,
              bold: true,
              size: 26,
              font: headingFont,
              color: accentHex,
            }),
          ],
        })
      );
    }

    if (section.body) {
      const bodyLines = section.body.split("\n");
      for (const line of bodyLines) {
        const bulletMatch = line.match(/^[\s]*[-•*]\s+(.*)/);
        if (bulletMatch) {
          children.push(
            new Paragraph({
              bullet: { level: 0 },
              spacing: { after: 60 },
              children: [
                new TextRun({
                  text: bulletMatch[1],
                  size: 22,
                  font,
                }),
              ],
            })
          );
        } else if (line.trim()) {
          children.push(
            new Paragraph({
              spacing: { after: 120 },
              children: [
                new TextRun({
                  text: line.trim(),
                  size: 22,
                  font,
                }),
              ],
            })
          );
        }
      }
    }
  }

  // Build footer
  const footerParagraphs = [
    new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [
        new TextRun({
          text: footerText,
          italics: true,
          size: 18,
          color: "888888",
          font,
        }),
      ],
    }),
  ];

  const doc = new Document({
    sections: [
      {
        children,
        footers: {
          default: new Footer({ children: footerParagraphs }),
        },
      },
    ],
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, `${filename}.docx`);
}

// ─── PDF Export ───

export async function exportToPdf(
  content: string,
  filename: string = "crisp-output",
  branding?: DocumentBranding
): Promise<void> {
  const { default: jsPDF } = await import("jspdf");

  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const maxWidth = pageWidth - margin * 2;
  let y = margin;

  const bodyFont = branding?.fontBody || "helvetica";
  const headingFont = branding?.fontHeading || bodyFont;
  const [pR, pG, pB] = hexToRgb(branding?.primaryColor || "#1e1e1e");
  const [aR, aG, aB] = hexToRgb(branding?.accentColor || "#10b981");
  const footerText = branding?.footerText || "Generated by Crisp";
  const showPageNumbers = branding?.showPageNumbers ?? true;
  let pageNumber = 1;

  // jsPDF only has a few built-in fonts; map common names to available ones
  const mapFont = (name: string) => {
    const lower = name.toLowerCase();
    if (lower.includes("times") || lower.includes("georgia") || lower.includes("garamond")) return "times";
    if (lower.includes("courier")) return "courier";
    return "helvetica";
  };

  const pdfBodyFont = mapFont(bodyFont);
  const pdfHeadingFont = mapFont(headingFont);

  const addPageIfNeeded = (requiredSpace: number) => {
    if (y + requiredSpace > pageHeight - margin - 10) {
      addFooter();
      doc.addPage();
      pageNumber++;
      y = margin;
    }
  };

  const addFooter = () => {
    doc.setFont(pdfBodyFont, "italic");
    doc.setFontSize(9);
    doc.setTextColor(150, 150, 150);
    doc.text(footerText, pageWidth / 2, pageHeight - 10, { align: "center" });
    if (showPageNumbers) {
      doc.text(`${pageNumber}`, pageWidth - margin, pageHeight - 10, { align: "right" });
    }
  };

  // Branded header
  if (branding?.headerStyle === "full") {
    // Accent bar at top
    doc.setFillColor(aR, aG, aB);
    doc.rect(0, 0, pageWidth, 3, "F");
    y = margin + 3;
  }

  if ((branding?.headerStyle === "branded" || branding?.headerStyle === "full") && branding?.companyName) {
    doc.setFont(pdfHeadingFont, "bold");
    doc.setFontSize(10);
    doc.setTextColor(pR, pG, pB);
    doc.text(branding.companyName, margin, y);
    y += 8;
  }

  // Logo (data URI → image)
  if (
    (branding?.headerStyle === "branded" || branding?.headerStyle === "full") &&
    branding?.logoUrl?.startsWith("data:")
  ) {
    try {
      doc.addImage(branding.logoUrl, "PNG", margin, y - 4, 15, 15);
      // Shift company name next to logo if both present
      if (branding.companyName) {
        doc.setFont(pdfHeadingFont, "bold");
        doc.setFontSize(10);
        doc.setTextColor(pR, pG, pB);
        doc.text(branding.companyName, margin + 18, y + 6);
      }
      y += 18;
    } catch {
      // Skip logo on error
    }
  }

  // Title
  const titleText = filename.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
  doc.setFont(pdfHeadingFont, "bold");
  doc.setFontSize(18);
  doc.setTextColor(pR, pG, pB);
  const titleLines = doc.splitTextToSize(titleText, maxWidth);
  addPageIfNeeded(titleLines.length * 8 + 10);
  doc.text(titleLines, pageWidth / 2, y, { align: "center" });
  y += titleLines.length * 8 + 10;

  // Divider in accent color
  doc.setDrawColor(aR, aG, aB);
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  const sections = parseSections(content);

  for (const section of sections) {
    if (section.title) {
      doc.setFont(pdfHeadingFont, "bold");
      doc.setFontSize(13);
      doc.setTextColor(aR, aG, aB);
      const headingLines = doc.splitTextToSize(section.title, maxWidth);
      addPageIfNeeded(headingLines.length * 6 + 8);
      doc.text(headingLines, margin, y);
      y += headingLines.length * 6 + 4;
    }

    if (section.body) {
      doc.setFont(pdfBodyFont, "normal");
      doc.setFontSize(11);
      doc.setTextColor(50, 50, 50);

      const bodyLines = section.body.split("\n");
      for (const line of bodyLines) {
        const bulletMatch = line.match(/^[\s]*[-•*]\s+(.*)/);
        const textToRender = bulletMatch ? `  \u2022  ${bulletMatch[1]}` : line.trim();

        if (!textToRender) {
          y += 3;
          continue;
        }

        const wrapped = doc.splitTextToSize(textToRender, maxWidth);
        addPageIfNeeded(wrapped.length * 5 + 2);
        doc.text(wrapped, margin, y);
        y += wrapped.length * 5 + 2;
      }
      y += 4;
    }
  }

  // Footer on last page
  addFooter();

  doc.save(`${filename}.pdf`);
}
